class FastReader:
    eof: bool
    remaining: str
    text: str
    pos: int
    length: int
    padded_length: bool

    def __init__(self, text: str) -> None: ...
    def peek(self) -> str: ...
    def ahead(self, offset: int) -> str: ...
    def peek2(self) -> str: ...
    def ahead2(self, offset: int) -> str: ...
    def startswith(self, literal: str) -> bool: ...
    def take(self) -> str: ...
    def take_exactly(self, count: int) -> str: ...
    def eat(self, literal: str) -> bool: ...
    def expect(self, literal: str) -> None: ...
    def digits(self) -> str: ...
    def length_prefixed(self) -> tuple[int, str]: ...
    def number(self, allow_negative: bool = True) -> str: ...
    def integer(self, allow_negative: bool = True) -> int: ...
    def seq_id(self) -> int: ...
    def fail(self, message: str) -> None: ...

def fast_msvc_identifier(text: str, pos: int, length: int) -> tuple[int, str] | None: ...
def fast_itanium_source_name(text: str, pos: int, length: int, is_ascii: bool) -> tuple[int, str] | None: ...
